"""sprint_2c_tests_table

Adds the `tests` table — persisted AI-generated (or user-authored) test
cases, mirroring the TestCase Pydantic schema in
app/ai/schemas/test_case.py (Implementation Plan §7.2). No API endpoints
persist to this table yet; this migration only adds the schema.

Revision ID: 642772c70444
Revises: 301323fa90b9
Create Date: 2026-08-22 22:45:05.032923

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '642772c70444'
down_revision: Union[str, Sequence[str], None] = '301323fa90b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('extractions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0.5'), nullable=False),
    sa.Column('ai_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), server_default=sa.text("'ai'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suite_id'], ['suites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tests_endpoint_id', 'tests', ['endpoint_id'], unique=False)
    op.create_index('ix_tests_suite_id', 'tests', ['suite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tests_suite_id', table_name='tests')
    op.drop_index('ix_tests_endpoint_id', table_name='tests')
    op.drop_table('tests')
    # ### end Alembic commands ###
