"""sprint_3_executions_tables

Adds `executions` and `execution_results` (PRD §14/§24, Sprint 3): a
deterministic, non-AI test-run record — one Execution per test run against
an Environment, with its ExecutionResult capturing the request sent, the
response received, and per-validation pass/fail.

Revision ID: 64fd55f9c4b4
Revises: 8657cfe2fca2
Create Date: 2026-08-23 21:59:16.031321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64fd55f9c4b4'
down_revision: Union[str, Sequence[str], None] = '8657cfe2fca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_executions_environment_id', 'executions', ['environment_id'], unique=False)
    op.create_index('ix_executions_test_id', 'executions', ['test_id'], unique=False)
    op.create_table('execution_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('test_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('request_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_execution_results_execution_id', 'execution_results', ['execution_id'], unique=False)
    op.create_index('ix_execution_results_test_id', 'execution_results', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_execution_results_test_id', table_name='execution_results')
    op.drop_index('ix_execution_results_execution_id', table_name='execution_results')
    op.drop_table('execution_results')
    op.drop_index('ix_executions_test_id', table_name='executions')
    op.drop_index('ix_executions_environment_id', table_name='executions')
    op.drop_table('executions')
    # ### end Alembic commands ###
